---
vms:
- name: master
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-master
- name: first
  box: centos-59-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent
- name: second
  box: ubuntu-server-10044-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent
